### ISSUE TITLE
CipherParams type

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#12]
Why is the [cipherParams](https://github.com/ably/ably-java/blob/master/src/io/ably/types/ChannelOptions.java#L8) attribute of `ChannelOptions` an `Object` when there is a type [CipherParams](https://github.com/ably/ably-java/blob/db50628fceb0af37c63c33693ab77dbb35d3c245/src/io/ably/util/Crypto.java#L52)?

**Comment by paddybyers** [comment]
Because that `CipherParams` type contains params for the default algorithm and mode. It is legitimate to have a different Cipher type, and a different set of parameters to configure it.

We could have an abstract base class or interface to give some non-Object type to all cipher params types, but it would contain nothing and I think that's pointless.

**Comment by mattheworiordan** [comment]
Fair enough
