### ISSUE TITLE
authorise signature for 0.8 is incorrect

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#186]
https://github.com/ably/ably-java/pull/185

**Comment by trenouf** [comment]
I agree it is wrong, but Simon said that we should not break compatibility within 0.8.x libraries.

Paddy said:
After discussion with @SimonWoolf we decided that we should not make a breaking change in the a minor release of the 0.8 library, given that it is widely used. Instead, we will correct the signature when 0.9 is released.

**Comment by mattheworiordan** [comment]
> After discussion with @SimonWoolf we decided that we should not make a breaking change in the a minor release of the 0.8 library, given that it is widely used. Instead, we will correct the signature when 0.9 is released.

@paddybyers I replied to your comment but for some reason it did not arrive.

I don't agree with this personally, if it's wrong and inconsistent with **every** other client library, and the arity of the other auth methods is fixed, then we should just go ahead and fix this.  Whilst it may be breaking, we need to remember that Java is strongly typed, so customers will not have silent failures, and also I very much doubt many are calling authorise directly now anyway.  I am unwilling to accept that is OK that our documentation states in https://www.ably.io/documentation/realtime/authentication#authorize that the Java def is `TokenDetails authorize(TokenParams tokenParams, AuthOptions authOptions)` and it's not.

If you are adamant we leave the arity as is, then I will accept unwillingly, but then the documentation needs to be fixed to introduce this inconsistency.

**Comment by trenouf** [comment]
I was wondering if there was some way of supporting both signatures simultaneously on 0.8. Suggestions:
1. With java method overloading, you can just define both. The problem is that authorise(null,null) gives a compile failure, which can be fixed by casting one of the nulls. Is that a problem? Does anyone do authorise(null,null) outside of our own library and test code?
2. A bit dodgier, but we could have a method that takes two Objects and run-time determines the types.

**Comment by paddybyers** [comment]
1) I don't like because code that previously compiled now fails to compile, so it's a breakage anyway. We just don't know if anyone is doing that.

2) I don't like because it's not really what you're supposed to do in a strongly typed language.

A breaking change at some point is unavoidable, so we might as well do it once, and properly.

**Comment by trenouf** [comment]
So, now or 0.9?

**Comment by mattheworiordan** [comment]
I vote now

**Comment by paddybyers** [comment]
> I vote now

I know.

**Comment by mattheworiordan** [comment]
> I know.

Yup, was just hoping to get a show of votes to confirm one way or the other.

**Comment by mattheworiordan** [comment]
@SimonWoolf @tcard can you please indicate what your preference would be here?  Given this is  a typed language my feeling is that whilst we are making a breaking change, we've [done this  before anyway](https://github.com/ably/ably-java/commit/7f0ad3962041bed01f49fcbbdfb5daf500eeca56).  

@paddybyers I assume you would prefer to leave as is then?

**Comment by paddybyers** [comment]
> I assume you would prefer to leave as is then?

I don't see why it's a good idea to make a breaking change in 0.8.x. We want customers to know that they can take bugfix releases at any time without breaking their code. 0.9 will fix it.

**Comment by SimonWoolf** [comment]
> can you please indicate what your preference would be here?

I would default to not making breaking API changes between patch versions.

We have done those before (in ably-js too), but that was when we had very few customers and they all knew they were using a service that hadn't been launched yet; that's no longer the case.

@mattheworiordan you've said above you're concerned about accuracy of the documentation -- but at least if the order swaps between 0.8 and 0.9, we will have document versioning, so we can make the docs correct for both minor versions. If the order swaps between 0.8.4 and 0.8.5, we can't; it will always be wrong for some set of people (unless we introduce patch-level versioning, and let's not do that...)

**Comment by mattheworiordan** [comment]
Ok, fine, leave as is then.  Do you think the old deprecated method https://github.com/ably/ably-java/pull/208#issuecomment-257278014 should have the correct parity or old incorrect parity?  I would say it should have the correct parity personally.

**Comment by tcard** [comment]
> I would default to not making breaking API changes in a patch version.

The problem is, we're conflating two meanings to our client libraries' major.minor versions: they refer both to the specific library version and to the generic specification version ("the IDL"). Obviously, those two meanings are in conflict when, as in this case, the library API and the IDL don't coincide, and then we're forced to choose what we break. In those cases I'd tend to go with sticking to the IDL, even at the expense of breaking builds if it can't be avoided via overloading, aliasing or something like that. Especially given that we are pre-1.0 and semver doesn't guarantee anything before 1.0.

In this particular case, given that we're just a few weeks away from releasing 0.9, maybe it's more practical to just wait to fix this.

**Comment by SimonWoolf** [comment]
No strong preference either way from me (deprecated methods for renames are less important in compiled languages anyway)

**Comment by trenouf** [comment]
I prefer new correct param order for the old deprecated method, but that might only be because that is what I have implemented so it is less work for me. :-)

**Comment by mattheworiordan** [comment]
This is no longer an issue as we decided to leave as is and change in 0.9
