### ISSUE TITLE
Test instructions

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#311]
Following the test instructions at https://github.com/ably/ably-java/tree/0-9-master#tests does not work.

Firstly it should state run `./gradlew ...` instead of `gradle ...`

Secondly, when I do run the tests it doesn't work:

```
./gradlew java:java:testRealtimeSuite

FAILURE: Build failed with an exception.

* What went wrong:
Project 'java' not found in project ':java'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.523 secs
jenkins@ci:~/jobs/ably-java/workspace$ ./gradlew java:testRealtimeSuite
:java:generateBuildConfig UP-TO-DATE
:java:compileBuildConfig UP-TO-DATE
:java:compileJava UP-TO-DATE
:java:processResources UP-TO-DATE
:java:classes UP-TO-DATE
:java:compileTestJava UP-TO-DATE
:java:processTestResources UP-TO-DATE
:java:testClasses UP-TO-DATE
:java:testRealtimeSuite FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':java:testRealtimeSuite'.
> No tests found for given includes: [*RealtimeSuite]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.899 secs
```

**Comment by paddybyers** [comment]
The document has been updated to refer to `gradlew`: https://github.com/ably/ably-java/commit/ebb140ee072cdd12cfcd5a436aadeb396d6b24ab

The failure to run was a result of a bug in the interim build running on staging. The confusing error message is from JUnit, but if you run with `--info` you can see that the issue was a failure of the system to respond to the `/apps` post to create the test app.
