### ISSUE TITLE
ConcurrentModificationException in 1.0

### ISSUE THREAD

**Issue by ousenko** [ably/ably-java#321]
@SimonWoolf @paddybyers Hey guys, could these crashes be related to https://github.com/ably/ably-java/issues/319 ?

```
Fatal Exception: java.util.ConcurrentModificationException
 Raw Text
java.util.HashMap$HashIterator.nextEntry (HashMap.java:787)
java.util.HashMap$ValueIterator.next (HashMap.java:819)
io.ably.lib.transport.ConnectionManager.setState (ConnectionManager.java:250)
io.ably.lib.transport.ConnectionManager.handleStateChange (ConnectionManager.java:710)
io.ably.lib.transport.ConnectionManager.notifyState (ConnectionManager.java:304)
io.ably.lib.transport.ConnectionManager.closeImpl (ConnectionManager.java:905)
io.ably.lib.transport.ConnectionManager.handleStateRequest (ConnectionManager.java:656)
io.ably.lib.transport.ConnectionManager.run (ConnectionManager.java:777)
java.lang.Thread.run (Thread.java:818)
```

```
Fatal Exception: java.util.ConcurrentModificationException
 Raw Text
java.util.HashMap$HashIterator.nextEntry (HashMap.java:787)
java.util.HashMap$ValueIterator.next (HashMap.java:819)
io.ably.lib.transport.ConnectionManager.setState (ConnectionManager.java:202)
io.ably.lib.transport.ConnectionManager.handleStateChange (ConnectionManager.java:503)
io.ably.lib.transport.ConnectionManager.run (ConnectionManager.java:588)
java.lang.Thread.run (Thread.java:818)
```

**Comment by paddybyers** [comment]
This looks like there is a listener for a channel state change event (eg detached, suspended) which is removing the channel. The `ConcurrentModificationException` occurs because the removal is made during the iteration of all channels.

There is an experimental fix for this here: https://github.com/ably/ably-java/tree/synchronised-channels. This simply makes all of the iterations synchronized, which could mean that a callback would block (ie deadlock) instead of raising an exception.

It's not going to be possible to spend more time on this issue before the next release but we can look at this again later.
