### ISSUE TITLE
Android, build and test documentation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#38]
@paddybyers please can you update the README ASAP for users to:
- Understand how to use the library with Android
- Build the JARs
- Run the test suite, including info relating to the encryption issues we have seen a few times

**Comment by mattheworiordan** [comment]
Travis needs to build Android and run Android tests, see https://docs.travis-ci.com/user/languages/android

**Comment by gokhanbarisaker** [comment]
@mattheworiordan Whether it is Android or pure Java, [JUnit tests will run on local JVM](http://developer.android.com/training/testing/unit-testing/local-unit-tests.html). We might run these tests using [AndroidJUnitRunner](https://google.github.io/android-testing-support-library/docs/androidjunitrunner-guide/), but they require a connected (virtual or physical) device. For that, [Cloud Test Lab](https://developers.google.com/cloud-test-lab/?hl=en) would be a better option

**Comment by paddybyers** [comment]
> Travis needs to build Android and run Android tests

There is no longer a separate Android build of the library.

The `android-test` subproject is set up to build and run the tests on Android with `AndroidJUnitRunner` which will work with a locally-connected device or emulator.

> Travis needs to build Android and run Android tests, see https://docs.travis-ci.com/user/languages/android

I'm not sure how well that Travis CI support will work for us because it takes over the building of the tests based on things you specify in the .yml instead of using the gradle configuration we provide. But I've not played with it so I don't know how flexible it is.

> For that, Cloud Test Lab would be a better option

@gokhanbarisaker if you have experience with that and recommend it, it would be worth trying out.

**Comment by mattheworiordan** [comment]
> For that, Cloud Test Lab would be a better option

Sure, but it is very handy to have one test suite that passes or fails, and I expect if we used Cloud Test Lab we'd need to have a separate job run.  If I am wrong, and you can integrate into the Travis CI tests, then please do go ahead

**Comment by paddybyers** [comment]
> I am guessing this is no longer an issue when #372 is merged?

I agree, I think we can close this
