### ISSUE TITLE
Ensure correct feedback to developer when malformed key is supplied

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-java#382]
Now it's possible to write 

`ably = new AblyRealtime("");` 

The app starts and tries to connect. Then a timeout happens, because the key doesn't exists. ~~We should check if the key passed as a parameter is not empty and in the correct format.~~ This doesn't help user to solve the problem and doesn't show what the problem is.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-418) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
Note that per https://docs.ably.io/client-lib-development-guide/features/#RSC1a , since `""` doesn't contain a colon, it should be interpreted as a token, which means there's no clientside format validation.

(I mean sure we could validate that the string isn't empty if we want, a valid token's never going to be the empty string. But shrug, not a big deal if we don't, and there certainly isn't any token validation we can/should do clientside beyond that)

**Comment by paddybyers** [comment]
It is interpreted as a token. I don't see what the error is.

What's the timeout?

**Comment by kavalerov** [comment]
Based on the conversation we had this morning, the real problem here is that timeout is not really a right behaviour in this case. We need to: 
1) check what is the behaviour currently
2) If behaviour is same as described in this ticket, we need to make sure that developer gets correct feedback (error message?) if malformed key is provided.
