### ISSUE TITLE
Add RTN20 support - react to operating system network connectivity events

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#415]
See https://docs.ably.io/client-lib-development-guide/features/#RTN20

**Comment by harrywiner1** [comment]
[] do setup run configuration run tests
[] run tests with command line
[] Write a test that fails without the feature then add the feature
[] Assertion based on the time taken to reconnect 
[] Get library working
[] Limit network interfaces are available
[] Rather than wait for platform to broadcast event, broadcast event programmatically

**Comment by paddybyers** [comment]
This is implemented in 1.1
