### ISSUE TITLE
More Encapsulation Needed

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#508]
Going through the README I notice the library has many **public** attributes. From an object-oriented point of view, this is unacceptable -- we will never be able to refactor/modify the internals of the SDK without causing compile-time problem for existing users. It's also a really bad smell which would make any experienced Java Dev avoid this library.

e.g. ``ably.connection`{{ should be }}`ably.connection()`{{ (we ommit the }}`get`` prefixes since they are just noise) and it should return an **interface**, not a class!

It boils down to a few pieces of advise:

* Users should work only through Java Interfaces returned by "accessor" methods.
* Access level of internal classes (which should not be used by the client) should be **package protected** -- that is, we should stop using Java packages for "keeping order". Java packages are primarily for access control but most Java Developers use them just to organize their classes, thus making any class public.
* Public classes used by the user should be thoroughly documented via **JavaDocs** explaining what the object is and how it should be used.

Please, take the above into consideration. It will of course affect the overall architecture but it's for the better, for sure.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-570) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
Please bear in mind you are coming at this from the perspective of a Java developer only, and not a polyglot API perspective which we are coming at this from. See the Ably IDL at https://docs.ably.io/client-lib-development-guide/features/#idl.   Our goal at Ably is to have a consistent API across all SDKs where possible, with exceptions only where necessary based on language idiomatic design / patterns / constraints.

> Going through the README I notice the library has many public attributes

Sure, we are aware of some of these, but actually need them for testing I believe.  Something we would prefer to avoid, but I understand unavoidable.  Instead of high level issues stating public methods are bad, please raise issues for specific methods, see where they are used, propose a workaround to make them private.  But please do your research first to understand why they are public.

> we will never be able to refactor/modify the internals of the SDK without causing compile-time problem for existing users

Well perhaps, but equally we have documentation of our APIs.  If customers are using undocumented public APIs, that's on them too, see https://docs.ably.io/client-lib-development-guide/features/#idl and comprehensive docs at www.ably.io/documentation.

> It's also a really bad smell which would make any experienced Java Dev avoid this library.

Well as above, please raise issues for specific public methods/attributes instead of broad-brush comments.

> e.g. ably.connection should be ably.connection() (we ommit the get prefixes since they are just noise) and it should return an interface, not a class!

Why do you say that?  A client has one connection object only.  Why should a single connection object not be made available as an attribute?  You say that is wrong, why?

> Users should work only through Java Interfaces returned by "accessor" methods.

Why?  `foo.bar` is not wrong.  Attributes exist for a reason, and they are `get` accessor methods.

> Access level of internal classes (which should not be used by the client) should be package protected -- that is, we should stop using Java packages for "keeping order". Java packages are primarily for access control but most Java Developers use them just to organize their classes, thus making any class public.

Please be specific again.  Which class has this issue, we can look at each case and comment.

> Public classes used by the user should be thoroughly documented via JavaDocs explaining what the object is and how it should be used.

Well thoroughly documented I disagree, but documented yes.  And that should be a separate issue to this as that has nothing to do with encapsultion.  If you propose adding Javadocs, with links to the canonical docs at www.ably.io/documentation for the classes / attributes / methods, I am a big supporter of this.  For example, see https://www.rubydoc.info/gems/ably/1.1.1, which is generated only from the Ruby code itself, see https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection.rb#L87 for example.

> Please, take the above into consideration. It will of course affect the overall architecture but it's for the better, for sure.

Please consider that a) we provide polyglot APIs, b) we need specifics, not high level thoughts, because I suspect in a lot of cases, there are reasons why slightly less than ideal decisions have been made, c) we appreciate feedback :)

**Comment by mattheworiordan** [comment]
@paddybyers would it be worth reviewing which public methods shouldn't be public methods and deciding which can be addressed? For example, a customer yesterday reported they are using `ably.auth.renew()`, which is undocumented and thus unsupported.  I agree that if people are using methods like this, we should do something now to proactively resolve this.

**Comment by paddybyers** [comment]
> we should do something now to proactively resolve this

I suspect that particular case is a throwback to the fact that this library was implemented first before the spec existed, and there's no reason for `Auth.renew()` to be public. Right now, we can deprecate it (so there will be a compile-time warning), and remove it in some future release.

There are definitely other places in the library where some methods are public because they are called from a different package, but are not part of the public API. In some cases, the callers are tests, but in other cases, it's other library code in another package.

**Comment by amihaiemil** [comment]
@mattheworiordan You're right, I should open more concrete tickets... I just got too excited, sorry! 

Just to address one question: 

> e.g. ably.connection should be ably.connection() (we ommit the get prefixes since they are just noise) and it should return an interface, not a class!

>> Why do you say that? A client has one connection object only. Why should a single connection object not be made available as an attribute? You say that is wrong, why?

It is wrong simply because the internals of the AblyRealtime object are exposed to the customer to use directly. We won't be able to refactor AblyRealtime, we won't be able to decorate the Connection, we won't be able to change the Connection's implementation (actually this is because Connection is a class, not an interface) etc. 

You've also said:

> Please bear in mind you are coming at this from the perspective of a Java developer only, and not a polyglot API perspective which we are coming at this from

Does this mean we are trying to have uniform code conventions and architecture across different SDKs written in different languages? Even so, I don't think there is a single language where public attributes are acceptable, hihi. 

Nevertheless, I'll take things one at a time. Thanks for your feedback!

**Comment by mattheworiordan** [comment]
> It is wrong simply because the internals of the AblyRealtime object are exposed to the customer to use directly. 

Sure, I get that, but the `Connection` object is in our control.  So we control what the consume has access to.

> We won't be able to refactor AblyRealtime

Why not?

> we won't be able to decorate the Connection

Do we need to? We own the Connection object and define the API in our spec.

> we won't be able to change the Connection's implementation (actually this is because Connection is a class, not an interface) etc.

Sure we can, a class encapsulates code that is private.  What do you mean?

> Does this mean we are trying to have uniform code conventions and architecture across different SDKs written in different languages?

Sure, as much as practically possible, unless for some idiomatic reason, we think it's a bad idea.

> Even so, I don't think there is a single language where public attributes are acceptable, hihi.

I think every language supports public attributes for a reason.  I think Java devs have become squeamish about using attributes because of how little control it can offer over how those getters are setters work.  Most other languages are quite comfortable with public attributes because under the hood they're just get and set methods anyway.  So this feels like a Java problem, not an every language problem to me.  I stand to be corrected, please do point me to some reading on the matter :)

**Comment by amihaiemil** [comment]
@mattheworiordan 

> Sure we can, a class encapsulates code that is private. What do you mean?

My bad. By "switching implementations" I meant to say changing the interface's implementation. You see, I've researched OOP quite a lot in the past few years and I've come to  2 simple rules (they have a huge, positive, I'd say, impact on the design, though): 

1. Always use interfaces. Any class in the code should implement an interface/all public methods of any class should be declared by an interface.

2. Never try to transform object A into object B. Rather, add a new implementation of B (which is actually in interface) based on A. 

These rules help avoid spaghetti code, "mapping" logic and so on. And of course, in order to properly implement these points, one needs encapsulation/private attributes. And one does not need getters and setters at all, but that's another story.

There are a few points in the lib where we could refactor code to use object rather than procedural code (for instance, building JSON bodies).

I'll open more concrete Issues, down the road. Until then, should we close this ticket or leave it open? WDYT?

**Comment by QuintinWillison** [comment]
This discussion is now over three years old. I'm pointing this out as part of the reasoning behind me closing this issue. I agree with much of what was raised at the time of issue creation, as well as within the ongoing discussion, however there is not enough specific detail here for us to estimate or prioritise this work. It's very abstract (pun, slightly, intended 😉). My hope is that if we manage to tackle everything under https://github.com/ably/ably-java/milestone/7 for version 2 of this SDK then we'll be in a much better place to start making small, incremental improvements to the API that naturally foster better encapsulation.
