### ISSUE TITLE
Build takes too long

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#510]
Running ``gradle build`` from the root directory on a fresh git clone takes too much time. It's "stuck" at 82% running tests for more than 5 minutes already. 

Building a Java SDK should be fast so we can get quick feedback about our changes. How could we reduce the build time? Running tests so slowly is also quite a smell -- unit tests should be quick (ideally, hundreds of tests should run in the order of seconds).

**Comment by mattheworiordan** [comment]
@amihaiemil but they are not unit tests. The only point of SDK tests is to ensure the SDK works with the actual endpoints, not fake endpoints.  Faking the endpoints would give you fast tests, but give you no guarantee the SDK actually works with the service endpoints.  So I am not sure what you are suggesting here?  Parallelisation is possible, but what else are you thinking?  It's easy at a high level to say "tests should be fast", but which test or group of tests are unnecessarily slow, and how would you propose making them faster exactly?

**Comment by amihaiemil** [comment]
@mattheworiordan I'm not sure what can be done, but it's surely a problem. I suggest we leave this ticket open and I'll suggestions here when I find something. 

So there integration tests with the real Ably API? You're right in that it doesn't make much sense to write  tests with a Mock API. Yet, I think it's beneficial to the architecture.

Knowing you will have to write tests that should work with both mock and real data, forces you as a developer to have better decoupling. Ideally, the tests should be identical with only a switch mechanism between the Mock API and real API. Furthermore, development would be faster -- let's say developers run the tests locally with Mock Data, rather than the Real Data and let only the CI server actually use the real Ably.

**Comment by mattheworiordan** [comment]
> Ideally, the tests should be identical with only a switch mechanism between the Mock API and real API

Ok, but developers will either a) not switch and falsely think they've written tests that work, b) will always do the switch which means we now have more code to maintain, and have the same performance issues + unit tests against mock time.

>  Furthermore, development would be faster -- let's say developers run the tests locally with Mock Data, rather than the Real Data and let only the CI server actually use the real Ably.

Sure, but it's faster at the expense of a) not knowing it will work, b) adding a shed load of complexity to generate the Mock Data, c) Mock Data is not possible without building a realtime server as well, which is incredibly complicated, so you only gain REST Mocks, where around 20% of the SDK complexity lies.

If you want speed, look at better parellisation.  I am all for that.  We could consider migrating to Github Actions, and getting things running in parallel. That's a good investment IMHO.

Building Mocks, that need to be kept in sync with the actual endpoints, which can only be verified by not running against the Mocks, seems like a big step backwards simply so that we can have the convenience of running tests locally quickly that we cannot trust.

**Comment by QuintinWillison** [comment]
This issue is not specific enough.

We do expect to make changes to our approach around testing across our client libraries, however those changes will be planned and focussed in nature. For now they're being discussed internally and will more likely surface in this repository as pull requests in the future.

If there are specific tests which are disproportionally slow at runtime then we can reactively create discrete issues for them individually, creating targeted areas to focus on.
