### ISSUE TITLE
HttpScheduler.AsyncRequest<T> Ignores withCredentials Parameter

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#517]
The class [HttpScheduler.AsyncRequest<T>](https://github.com/ably/ably-java/blob/6edf71728f42b9379d7a57d55aa99de8d431e119/lib/src/main/java/io/ably/lib/http/HttpScheduler.java#L238) takes ``withCredentials`` boolean flag as constructor parameter, but does nothing with it. 

Should we remove it or implement some logic based on it?

**Comment by paddybyers** [comment]
My memory of this is that I wanted to make a change whereby the credentials were passed down through the Http framework from the caller to the lower layers explicit as credentials arguments, rather than being added to the headers or params. This would allow the credentials to be applied where needed, and would also generalise to handling of proxy credentials as well as the regular endpoint credentials.

However, this work was never completed, and we were left with this vestigial `withCredentials` argument that's unused.

I think it should be deleted.

**Comment by amihaiemil** [comment]
@paddybyers ok :) I'll make a PR today
