### ISSUE TITLE
ClientOptions should be a Builder State Machine

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#527]
I suppose there are some rules regarding ClientOptions, right? E.g. if option A is set, then option B cannot be set, as there would be a conflict in business logic. 

For instance, ``restHost`` and ``realtimeHost`` should be set only in development environments or tests. So they should be visible and settable in a ClientOptions builder returned by ``ClientOptions.development()``.

This approach would ensure that all the given options are correct and algorithms throughout the library can rely that e.g. if TLS is true, then the port is surely ``443``.

As an iteration approach, we can first ``@Deprecate`` the current ClientOptions and build another one. 

Read more about this State Machine approach [here](https://blog.frankel.ch/builder-pattern-finite-state-machine/) (by Nicholas Fränkel, Java author and speaker)

**Comment by mattheworiordan** [comment]
I am really not a huge fan of this idea.  `ClientOptions` is a stateless and simple object.  In almost all other languages, this is just a struct or plain object, because it really doesn't need that level of complexity.  If there are conflicting issues, or validation required on configuration of the `ClientOptions`, they can be easily validated when provided to the constructor, and importantly, this can be done in a portable fashion across every language.

I'm interested to know, what do you think we achieve by making this object more complex, changing attributes to `get` and `set` methods, and using a pattern that is less portable across languages?

**Comment by amihaiemil** [comment]
> I'm interested to know, what do you think we achieve by making this object more complex, changing attributes to get and set methods, and using a pattern that is less portable across languages?

1. When the final ``.build()`` method is called you get a ``ClientOptions`` object which is properly built. It has all the mandatory attributes, and maybe optional ones, and they do not conflict. As an example I gave in the description, we would know for sure that if ```tls`` is true then ``port`` is for sure 443.

If the object is not properly built, the user gets an exception right away. 

2. When building the ``ClientOptions`` we can "show" the settable attributes when it is correct to set them. As in the description with ``restHost`` and ``realtimeHost``.

the above 2 points are a plus for the user, he/she is guided by the builder and shown exactly what are the possible configuration options/combinations.

3. For us: our algorithms become lighter since we don't need any validation logic. You say "ClientOptions, they can be easily validated when provided to the constructor" -- but this means a bunch of ``if/else`` statements here and there which are only polutting the code. 

4. There is another argument, a bit broader: this pattern would build an immutable object. The builder itself could be immutable. Immutable objects are thread-safe, we get rid of a big pain. Mutable objects, especially with public fields, are a ticking-bomb in a multi-threaded environment.

I don't really understand your argument of having the code as similar as possible across languages. You want good Java devs, good Ruby devs etc, each working on their own library which should be built according to the language's best practices, which differ.

Nonetheless, Paddy also told me these kind of tickets are not a priority. I'm not going to make changes until they are, they are just suggestions from my side. :)

**Comment by QuintinWillison** [comment]
While I agree with @amihaiemil that this is a specific area of the client library API that could be improved to be more idiomatic to a Java developer, there is a much wider architectural discussion to be had here that impacts the Ably developer experience across all of our client libraries and - of course - our [client library features specification](https://docs.ably.io/client-lib-development-guide/features/).

We are having those discussions internally. We're identifying the keys for a structured approach towards balancing the needs across our client libraries between:

1. conforming with the client library features specification wherever possible, ensuring we can talk about interactions with the Ably service in a predictable way no matter which client library we are developing with; and
2. improving the developer experience for a given language and/or platform so that our client library for that environment presents as few surprises to those developers as possible - allowing them to get up to speed in an idiomatic manner and for things to 'just work' as they would expect them to

So I'm going to close this issue as it's too specific until we have a wider plan in place. We know this is a (possible) pain point depending on the type of language and runtime being developed against so I'm confident this will re-surface if we identify that this is a high value pain point to target.
