### ISSUE TITLE
Support for encryption of shared preferences

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#593]
We persist [secrets](https://github.com/ably/ably-java/blob/1399a98d6d0e7c5b75218e945c284708940ec1f0/android/src/main/java/io/ably/lib/push/LocalDevice.java#L123) (e.g. `ABLY_DEVICE_SECRET`) and [tokens](https://github.com/ably/ably-java/blob/1399a98d6d0e7c5b75218e945c284708940ec1f0/android/src/main/java/io/ably/lib/push/LocalDevice.java#L113) (e.g. `ABLY_DEVICE_IDENTITY_TOKEN`) to `SharedPreferences` without encryption or any other form of obfuscation, in terms of both values and the keys they are stored under.

This has been raised by a customer who discovered this when doing a security test after they "rooted" their app.

When Ably first implemented `LocalDevice` storage, there wasn't anything we deemed suitable that would give any material increase in security, hence the implementation was kept simple.

Perhaps the best solution going forward would be to allow app developers to override the storage I/O in order to provide their own encryption and/or platform service designed for secrets. Such a provider might be as simple as:

```java
interface Storage {
    void write(String key, String value);
    String read(String key, String defaultValue);
}
```

We would provide a default implementation using shared preferences, as we do currently.

I would also suggest we look at fixing #562 when we work on this as it's in the same area of the codebase.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-589) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
It wasn't very clear to me what this issue or related PR was doing. After reading the diff of the PR, I noticed in `ClientOptions`: 
https://github.com/ably/ably-java/blob/d9ad0e1923fbfa5ad85eecf07be52fcc5b470b09/lib/src/main/java/io/ably/lib/types/ClientOptions.java#L200-L204

So this issue only allows users to specify a custom implementation of `Storage`, and doesn't actually do anything with encryption. Users would have to add logic to encrypt the data themselves. This is probably because the clients shouldn't really encrypt the data using a symmetric key which is available locally, since this can be found and used by a threat actor.

**Comment by sacOO7** [comment]
Actually, there is a official way to encrypt shared pref. With a key, that's not exposed to a user.
https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences
Also, there was a discussion related to this, and it was decided that we will not do the encryption, since it adds more efforts and complexity to the code.

**Comment by ben-xD** [comment]
Okay thanks for adding that detail, it seems like we missed an opportunity to make things easier for the users who care about security here 😅. IMHO after browsing for some example code, it's not complicated, and I think you agree with me based on my comment above.
