### ISSUE TITLE
HAS_BACKLOG flag

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#6]
Doesn't seem to be used, see https://github.com/ably/ably-java/blob/2e81470a464b6ec5f888a1b0941d3bca59cb2b37/src/io/ably/types/ProtocolMessage.java#L49.  Should it be there if it's not implemented?

**Comment by paddybyers** [comment]
The flag is set by the realtime system if, upon reattach, there are catchup messages to be sent.

Right now the client library doesn't do anything in response, because it simply processes the messages as they are received. However, in future I think there may be a benefit in indicating to the client in some way that there are catchup messages.

So there isn't anything "not implemented" except what we haven't specified yet.

If you think having the flag declared is potentially confusing then we can remove it.

**Comment by mattheworiordan** [comment]
Nope, leave it in, but can you please update the [protocol docs](http://docs.ably.io/client-lib-development-guide/protocol/) to reflect this before closing?
