### ISSUE TITLE
Automatic presence re-enter after network connection is back does not work

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-java#857]
We've discovered that a channel's presence is not automatically re-entered once you lose an internet connection and then it comes back on. After some further investigation, it turns out that this feature was working on older versions of `ably-java` SDK but it stopped working since version `1.2.2`. Looking at the [release notes](https://github.com/ably/ably-java/releases/tag/v1.2.2) of version `1.2.2` the most likely cause of this issue is the "Bump protocol version to 1.2".

**Steps to reproduce:**
- Create an `AblyReatlime` instance
- Join a channel's presence
- Verify that the client has joined the channel's presence (e.g. with the Ably dev dashboard)
- Turn the internet connection off
- Wait for the automatic "leave" event on the channel's presence
- Turn the internet connection on
- Wait for the automatic "enter" event

What should happen: The client should automatically re-enter the channel's presence after a few seconds
What happens: The client never re-enters the channel's presence

**Comment by paddybyers** [comment]
The relevant requirement is https://sdk.ably.com/builds/ably/specification/main/features/#RTP17c.

There is no test for this requirement, and no mention of this spec item in any historical PR.

There are two existing tests that mention RTP17:
- https://github.com/ably/ably-java/blob/main/lib/src/test/java/io/ably/lib/test/realtime/RealtimePresenceTest.java#L2095
- https://github.com/ably/ably-java/blob/main/lib/src/test/java/io/ably/lib/test/realtime/RealtimePresenceTest.java#L2767

Neither tests RTP17c specifically, and both are currently ignored.

**Comment by QuintinWillison** [comment]
@KacperKluka tried [our version `1.2.19` release](https://github.com/ably/ably-java/releases/tag/v1.2.19) in AAT and has discovered that this issue is still not fixed. In further discussion with @paddybyers and @SimonWoolf in [this Slack thread (internal)](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1669272796096359) we have discovered that we should have reverted to protocol `1.0`, not `1.1` as was the fix attempted in #858:

> serverside, `hasClientsidePresenceAutoReEnter` is assumed to be true for `>= 1.1` for most client libs, or `>= 0.9` for js

I am therefore reopening this issue and another PR will be inbound shortly.
